#!/bin/bash
PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:~/bin
export PATH
if [ ! -n "$1" ]
	then
	echo "vpn start    启动"
	echo "vpn stop     停止"
	echo "vpn restart  重启"
elif [ $1 == "start" ]
	then
	echo "正在启动"
	lnmp start >/dev/null 2>&1
	nohup /vpnserver/cmd/star.sh & >/dev/null 2>&1
	/vpnserver/mproxy-kangml -l 8080 -d >/dev/null 2>&1
	#/vpnserver/mproxy-kangml -l 137 -d >/dev/null 2>&1
	/vpnserver/mproxy-kangml -l 138 -d >/dev/null 2>&1
	/vpnserver/vpnserver start >/dev/null 2>&1
	echo "启动成功"
elif [ $1 == "stop" ]
	then
	echo "正在停止"
	lnmp stop >/dev/null 2>&1
	killall -9 star.sh >/dev/null 2>&1
	killall -9 cmdtool >/dev/null 2>&1
	killall -9 mproxy-kangml >/dev/null 2>&1
	/vpnserver/vpnserver stop >/dev/null 2>&1
	echo "停止成功"
elif [ $1 == "restart" ]
	then
	echo "正在重启"
	lnmp restart >/dev/null 2>&1
	killall -9 star.sh >/dev/null 2>&1
	killall -9 cmdtool >/dev/null 2>&1
	killall -9 mproxy-kangml >/dev/null 2>&1
	/vpnserver/vpnserver stop >/dev/null 2>&1
	sleep 2
	nohup /vpnserver/cmd/star.sh & >/dev/null 2>&1
	/vpnserver/mproxy-kangml -l 8080 -d >/dev/null 2>&1
	#/vpnserver/mproxy-kangml -l 137 -d >/dev/null 2>&1
	/vpnserver/mproxy-kangml -l 138 -d >/dev/null 2>&1
	/vpnserver/vpnserver start >/dev/null 2>&1
	echo "重启成功"
fi
